ci: add e2e test
celestiaorg/optimism pull request #121
Opened 2023-05-24 21:10 UTC by tuxcanfly

## Overview

This PR adds the e2e test from `op-e2e` package to the CI.

Fixes #38 

## Checklist

- [ ] New and updated code has appropriate documentation
- [ ] New and updated code has new and/or updated testing
- [ ] Required CI checks are passing
- [ ] Visual proof for any user facing features like CLI or documentation updates
- [ ] Linked issues closed with keywords

2023-05-29 18:44 UTC, tuxcanfly commented
`TestCrossLayerUser` seems to be a bit flaky, will investigate that later.

2023-05-30 13:36 UTC, MSevey commented on .github/workflows/close-stale.yml
I think this is fine to leave in

2023-05-30 13:42 UTC, MSevey requested changes
This PR contains multiple scopes that we should split out.

adding e2e testing, adding housekeeping workflows, and removing optimism workflows.

We should split this out into 3 PRs so that we can better test them as well as discuss them.

I'm not sure if we should just delete all the optimism workflows. We are an integration built on top of them so there is probably useful workflows to continue using. 

I would 
1. revert all the deletions and we can have that conversation separately.
2. open a second PR with the proposed new housekeeping workflows
3. make sure this PR is just the new e2e testing scope.

2023-05-30 13:42 UTC, MSevey commented on .github/workflows/fork-sync.yml
we should leave this in

2025-12-03 22:51 UTC, closed without merging